### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jswalens** [kenpratt/rusty_scheme#2]
I'm using your interpreter as "inspiration" for some stuff I'm doing. It'd be great if you could attach a license to it.

**Comment by kenpratt** [comment]
Sorry about that, I usually add MIT, but clearly forgot. Just added it.

Feel free to reach out of you have any questions! My email is ken@kenpratt.net.

**Comment by jswalens** [comment]
Thanks!

2016-05-11 17:08 GMT+02:00 Ken Pratt notifications@github.com:
