### ISSUE TITLE
Examples on how to bind rust functions?

### ISSUE THREAD

**Issue by lephyrius** [kenpratt/rusty_scheme#3]
Is this an embeddable scheme?
If so is there a small example on how to bind a rust function and call it from scheme?

**Comment by lephyrius** [comment]
Bleh! Looks like just a toy implementation. :( Sorry!

**Comment by ken-stripe** [comment]
Sorry @lephyrius -- yes this was just a for-fun project, and is a pretty narrow slice of functionality. It would be quite easy to extend to call rust functions, if your use case is on the simple side and you don't need much of the stdlib/types in Scheme.

**Comment by kenpratt** [comment]
Sorry @lephyrius -- yes this was just a for-fun project, and is a pretty narrow slice of functionality. It would be quite easy to extend to call rust functions, if your use case is on the simple side and you don't need much of the stdlib/types in Scheme.
